// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.northwind.model;

import org.northwind.model.Customer;
import org.northwind.model.Customer_Roo_Jaxb_Entity;

privileged aspect Customer_Roo_Jaxb_Entity {
    
    /*
     * This Aspect takes the lower precedence
     */
    declare precedence: *, Customer_Roo_Jaxb_Entity;
    
}
