// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.northwind.model;

import org.northwind.model.Employee;
import org.northwind.model.Employee_Roo_Jaxb_Entity;

privileged aspect Employee_Roo_Jaxb_Entity {
    
    /*
     * This Aspect takes the lower precedence
     */
    declare precedence: *, Employee_Roo_Jaxb_Entity;
    
}
