// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.northwind.model.dod;

import javax.persistence.EntityManager;
import org.northwind.model.dod.CategoryDataOnDemand;
import org.northwind.model.dod.CityDataOnDemand;
import org.northwind.model.dod.CountryDataOnDemand;
import org.northwind.model.dod.CustomerDataOnDemand;
import org.northwind.model.dod.CustomerOrderDataOnDemand;
import org.northwind.model.dod.DataOnDemandConfiguration;
import org.northwind.model.dod.EmployeeDataOnDemand;
import org.northwind.model.dod.OrderDetailDataOnDemand;
import org.northwind.model.dod.PartyDataOnDemand;
import org.northwind.model.dod.ProductDataOnDemand;
import org.northwind.model.dod.PurchaseOrderDataOnDemand;
import org.northwind.model.dod.RegionDataOnDemand;
import org.northwind.model.dod.ReportDataOnDemand;
import org.northwind.model.dod.ShipperDataOnDemand;
import org.northwind.model.dod.SoldProductDataOnDemand;
import org.northwind.model.dod.StoreDataOnDemand;
import org.northwind.model.dod.SupplierDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;

privileged aspect DataOnDemandConfiguration_Roo_JpaDataOnDemandConfiguration {
    
    declare @type: DataOnDemandConfiguration: @TestConfiguration;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private EntityManager DataOnDemandConfiguration.entityManager;
    
    /**
     * TODO Auto-generated constructor documentation
     * 
     * @param entityManager
     */
    @Autowired
    public DataOnDemandConfiguration.new(EntityManager entityManager) {
        setEntityManager(entityManager);
    }

    /**
     * TODO Auto-generated method documentation
     * 
     * @return EntityManager
     */
    public EntityManager DataOnDemandConfiguration.getEntityManager() {
        return entityManager;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entityManager
     */
    public void DataOnDemandConfiguration.setEntityManager(EntityManager entityManager) {
        this.entityManager = entityManager;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CategoryDataOnDemand
     */
    @Bean
    public CategoryDataOnDemand DataOnDemandConfiguration.categoryDataOnDemand() {
        return new CategoryDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CityDataOnDemand
     */
    @Bean
    public CityDataOnDemand DataOnDemandConfiguration.cityDataOnDemand() {
        return new CityDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CountryDataOnDemand
     */
    @Bean
    public CountryDataOnDemand DataOnDemandConfiguration.countryDataOnDemand() {
        return new CountryDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CustomerDataOnDemand
     */
    @Bean
    public CustomerDataOnDemand DataOnDemandConfiguration.customerDataOnDemand() {
        return new CustomerDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CustomerOrderDataOnDemand
     */
    @Bean
    public CustomerOrderDataOnDemand DataOnDemandConfiguration.customerOrderDataOnDemand() {
        return new CustomerOrderDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return EmployeeDataOnDemand
     */
    @Bean
    public EmployeeDataOnDemand DataOnDemandConfiguration.employeeDataOnDemand() {
        return new EmployeeDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return OrderDetailDataOnDemand
     */
    @Bean
    public OrderDetailDataOnDemand DataOnDemandConfiguration.orderDetailDataOnDemand() {
        return new OrderDetailDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return PartyDataOnDemand
     */
    @Bean
    public PartyDataOnDemand DataOnDemandConfiguration.partyDataOnDemand() {
        return new PartyDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ProductDataOnDemand
     */
    @Bean
    public ProductDataOnDemand DataOnDemandConfiguration.productDataOnDemand() {
        return new ProductDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return PurchaseOrderDataOnDemand
     */
    @Bean
    public PurchaseOrderDataOnDemand DataOnDemandConfiguration.purchaseOrderDataOnDemand() {
        return new PurchaseOrderDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return RegionDataOnDemand
     */
    @Bean
    public RegionDataOnDemand DataOnDemandConfiguration.regionDataOnDemand() {
        return new RegionDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ReportDataOnDemand
     */
    @Bean
    public ReportDataOnDemand DataOnDemandConfiguration.reportDataOnDemand() {
        return new ReportDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ShipperDataOnDemand
     */
    @Bean
    public ShipperDataOnDemand DataOnDemandConfiguration.shipperDataOnDemand() {
        return new ShipperDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return SoldProductDataOnDemand
     */
    @Bean
    public SoldProductDataOnDemand DataOnDemandConfiguration.soldProductDataOnDemand() {
        return new SoldProductDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return StoreDataOnDemand
     */
    @Bean
    public StoreDataOnDemand DataOnDemandConfiguration.storeDataOnDemand() {
        return new StoreDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return SupplierDataOnDemand
     */
    @Bean
    public SupplierDataOnDemand DataOnDemandConfiguration.supplierDataOnDemand() {
        return new SupplierDataOnDemand(getEntityManager());
    }
    
}
