// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.northwind.model.dod;

import java.math.BigDecimal;
import java.util.Calendar;
import java.util.GregorianCalendar;
import org.northwind.model.Employee;
import org.northwind.model.Product;
import org.northwind.model.PurchaseOrder;
import org.northwind.model.dod.PurchaseOrderFactory;

privileged aspect PurchaseOrderFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link PurchaseOrder} with the given index.
     * 
     * @param index position of the PurchaseOrder
     * @return a new transient PurchaseOrder
     */
    public PurchaseOrder PurchaseOrderFactory.create(int index) {
        PurchaseOrder obj = new PurchaseOrder();
        setEmployee(obj, index);
        setOrderDate(obj, index);
        setProduct(obj, index);
        setQuantity(obj, index);
        setUnitCost(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void PurchaseOrderFactory.setEmployee(PurchaseOrder obj, int index) {
        Employee employee = null;
        obj.setEmployee(employee);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void PurchaseOrderFactory.setOrderDate(PurchaseOrder obj, int index) {
        Calendar orderDate = Calendar.getInstance();
        obj.setOrderDate(orderDate);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void PurchaseOrderFactory.setProduct(PurchaseOrder obj, int index) {
        Product product = null;
        obj.setProduct(product);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void PurchaseOrderFactory.setQuantity(PurchaseOrder obj, int index) {
        Integer quantity = new Integer(index);
        obj.setQuantity(quantity);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void PurchaseOrderFactory.setUnitCost(PurchaseOrder obj, int index) {
        BigDecimal unitCost = BigDecimal.valueOf(index);
        obj.setUnitCost(unitCost);
    }
    
}
