// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.northwind.model.dod;

import org.northwind.model.dod.StoreDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect StoreDataOnDemand_Roo_Configurable {
    
    declare @type: StoreDataOnDemand: @Configurable;
    
}
