// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.northwind.model.dto;

import io.springlets.format.EntityFormat;
import org.northwind.model.dto.ShipperPhoneFormBean;

privileged aspect ShipperPhoneFormBean_Roo_DTO {
    
    declare @type: ShipperPhoneFormBean: @EntityFormat;
    
}
